name: Connexion GitHub -> Alwaysdata

on:
  push:
    branches:
      - main # Changer si elle marche pas mais normalement j'ai tout push dessus

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/
            echo "✅ Connexion OK depuis GitHub Actions"
